CREATE TABLE data_srcs ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
DataSrc_ID text unique,
Authors text,
Title text,
Year text,
Journal text,
Vol_City text,
Issue_State text,
Start_Page text,
End_Page text);
